repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.21
    hooks:
      - id: mdformat
        args: [--wrap=80]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-tables
